### ISSUE TITLE
Add initial code for this plugin

### ISSUE THREAD

**Issue by rhuss** [knative-sandbox/kn-plugin-diag#1]
@cdlliuy could you please create a PR for the initial code ?

**Comment by cdlliuy** [comment]
@rhuss ,  is PR #3  for the initial setup?  I just checked in a simple markdown?  should I check in the initial golang code?

**Comment by rhuss** [comment]
Yes, if you send in the code of the original plugin as a PR that would be very helpful as we then can setup the full build process.

**Comment by rhuss** [comment]
I think we are good, as the code has been already submitted.
